parameters:
  mode: jmeter

steps:
  - ${{ if and(ne(parameters.mode,'tests'),ne(parameters.mode,'jmeter_dynamic')) }}:
    - task: AzureCLI@2
      condition: always()
      displayName: Delete dedicated nodepool
      inputs:
        azureSubscription: $(armServiceConnection)
        scriptType: bash
        scriptPath: $(System.DefaultWorkingDirectory)/repos/$(repoName)/path/to/jmeter/config/custom/steps/delete_nodepool.sh
        arguments: crux$(Build.BuildID) $(cluster_name) $(rgroup)

  - ${{ if and(ne(parameters.mode,'tests'),eq(parameters.mode,'jmeter_dynamic')) }}: #dynamic cluster name cname becomes available:
      - task: AzureCLI@2
        condition: always()
        displayName: Delete dedicated nodepool
        inputs:
          azureSubscription: $(armServiceConnection)
          scriptType: bash
          scriptPath: $(System.DefaultWorkingDirectory)/repos/$(repoName)/path/to/jmeter/config/custom/steps/delete_nodepool.sh
          arguments: crux$(Build.BuildID) $(cname) $(rgroup)