parameters:
  mode: jmeter

steps:
  - ${{ if and(ne(parameters.mode,'tests'),ne(parameters.mode,'jmeter_dynamic')) }}:
    - task: AzureCLI@2
      displayName: Create dedicated nodepool
      inputs:
        azureSubscription: $(armServiceConnection)
        scriptType: bash
        scriptPath: $(System.DefaultWorkingDirectory)/repos/$(repoName)/path/to/jmeter/config/custom/steps/create_nodepool.sh
        arguments: crux$(Build.BuildID) $(cluster_name) crux.usage jmeter $(rgroup) $(scale_up_replicas) $(clusterNodeSize)
                   #nodepool_name       #cluster_name   #crux_label #crux_label_value #resource_group #scale_up_replicas #node_size

  - ${{ if and(ne(parameters.mode,'tests'),eq(parameters.mode,'jmeter_dynamic')) }}: #dynamic cluster name cname becomes available
      - task: AzureCLI@2
        displayName: Create dedicated nodepool
        inputs:
          azureSubscription: $(armServiceConnection)
          scriptType: bash
          scriptPath: $(System.DefaultWorkingDirectory)/repos/$(repoName)/path/to/jmeter/config/custom/steps/create_nodepool.sh
          arguments: crux$(Build.BuildID) $(cname) crux.usage jmeter $(rgroup) $(scale_up_replicas) $(clusterNodeSize)
          #nodepool_name       #cluster_name   #crux_label #crux_label_value #resource_group #scale_up_replicas #node_size
