parameters:
  mode: jmeter

steps:
  - ${{ if not(eq(parameters.mode,'tests')) }}:
    - task: AzureCLI@2
      displayName: Create dedicated nodepool
      inputs:
        azureSubscription: $(armServiceConnection)
        scriptType: bash
        scriptPath: $(System.DefaultWorkingDirectory)/repos/$(repoName)/path/to/jmeter/config/custom/steps/create_nodepool.sh
        arguments: crux$(Build.BuildID) $(cluster_name) crux.usage jmeter $(rgroup) $(scale_up_replicas) $(clusterNodeSize) cname
                   #nodepool_name       #cluster_name   #crux_label #crux_label_value #resource_group #scale_up_replicas #node_size


