parameters:
  mode: jmeter
steps:
  - ${{ if not(eq(parameters.mode,'jmeter_dynamic')) }}:
    - task: AzureCLI@2
      displayName: Prepare nodepool
      inputs:
        azureSubscription: $(armServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
           nodepool_name=crux$(Build.BuildID)
           cluster_name=k8
           resource_group=jmeter-group
           node_count=$(($(scale_up_replicas)+1)) # + 1 for the master
           node_size=Standard_D2_v2
           echo "Create dedicated pool on $cluster_name - $nodepool_name with $node_count nodes sized as $node_size"
           echo "az aks nodepool add --resource-group $resource_group --cluster-name $cluster_name  --name $nodepool_name --node-count $node_count --node-vm-size $node_size --labels crux.usage=jmeter"
           az aks nodepool add --resource-group "$resource_group" --cluster-name "$cluster_name"  --name "$nodepool_name" --node-count "$node_count" --node-vm-size "$node_size" --labels crux.usage=jmeter
           echo "Available pools: "
           az aks nodepool list -g "$resource_group" --cluster-name "$cluster_name" --output table