jobs:
  - job: Debug
    condition: and(succeeded(), eq('${{ parameters.debug }}', true))
    displayName: Mode selection
    steps:
      - bash: |
          echo "Run mode selected:"  ${{ parameters.mode }}
          echo "Debug:"  ${{ parameters.debug }}
          echo "Pool:"  ${{ parameters.linux_pool }}
        displayName: Display selected mode

  - ${{ if not(eq(parameters.mode,'tests')) }}: #jmeter variants
      - template: run.jmeter.kubernetes.template.yaml
        parameters:
          mode: ${{ parameters.mode }}
          linux_pool: ${{ parameters.linux_pool }}
  - ${{ if eq(parameters.mode,'tests') }}:
      - template: run.jmeter.kubernetes.template.tests.yaml
      - template: run.jmeter.kubernetes.template.yaml
        parameters:
          mode: ${{ parameters.mode }}
