parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: jmeter

  - name: linux_pool
    type: string
    default: microsoft_hosted

jobs:
  - job: Experimental
    timeoutInMinutes: 8
    cancelTimeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-latest'
    displayName: Experimental
    variables:
      - template: pipelines/azure/templates/default.variables.yaml@crux
        parameters:
          mode: ${{ parameters.mode }}

    steps:
      - template: pipelines/azure/templates/steps/step.crux_clone.yaml@crux