# This pipeline requires azure service connection of type "kubernetes service"
# Remember to have 1-1 jmeter service to k8 node (VM)/pod ratio - otherwsie some slaves can crash due to lack of resources

name: $(BuildID)
trigger: none
resources:
  repositories:
    - repository: crux
      type: github
      name: ObjectivityLtd/crux
      #ref: refs/tags/0.3.3
      ref: refs/heads/feature/arm
      endpoint: crux

    - repository: tests
      type: github
      name: ObjectivityLtd/jmeter_simple_test
      #ref: refs/tags/0.3.2
      #ref: refs/heads/feature/on_off_pipeline_steps
      endpoint: crux


parameters:
- name: debug
  type: boolean
  default: false

- name: mode
  default: jmeter_dynamic
  values:
    - tests
    - jmeter
    - jmeter_dynamic
- name: data_file
  type: string
  default: path/to/jmeter/test_data/sample_data.csv
  values:
    - path/to/jmeter/test_data/sample_data.csv

- name: jmeter_slaves
  default: 1
  type: number

- name: jmx
  default: path/to/jmeter/script/bing.jmx
  type: string

- name: thresholds_file
  default: path/to/jmeter/config/thresholds.properties
  type: string

- name: jmeter_args
  default: "-Gthreads=1 -Gloops=1"
  type: string

- name: connection
  default: k8con2
  type: string

variables:
  cluster_namespace: default
  kubernetesServiceConnection: ${{ parameters.connection }}
  scale_up_replicas: ${{ parameters.jmeter_slaves }}
  data_file: $(repoName)/${{ parameters.data_file }}
  thresholds_file: $(repoName)/${{ parameters.thresholds_file }}
  jmeter_args: ${{ parameters.jmeter_args }}
  repoName: jmeter_simple_test
  cruxRepoName: crux
  scenario: $(repoName)/${{ parameters.jmx }}
  #for mode with dynamic resource creation
  armServiceConnection: mygroup
  clusterNodeSize: Standard_D2_v2
  clusterNodeNumber: 2
  devOpsOrg: gstarczewski
  devOpsProject: jmeter
  devOpsPatUser: gstarczewski
  devOpsPat: $(pat)
  rgroup: jmeter-group

jobs:
  - template: pipelines/azure/templates/run.mode.selector.yaml@crux
    parameters:
      mode: ${{ parameters.mode }}
      debug: ${{ parameters.debug }}