name: $(BuildID)
trigger:
  batch: 'true'
  branches:
    include:
      - '*'

#specify where your tests reside, set both crux and tests version
resources:
  repositories:
    - repository: crux
      type: github
      name: ObjectivityLtd/crux
      #ref: refs/tags/0.4.1
      ref: refs/heads/feature/parametrization
      endpoint: crux

    - repository: tests
      type: github
      name: ObjectivityLtd/jmeter_simple_test
      #ref: refs/tags/0.3.2
      ref: refs/heads/feature/parametrization
      #ref: refs/tags/0.4.1
      endpoint: crux

#parameters available for selection when you run the pipeline
parameters:

- name: mode
  default: jmeter
  values:
    - jmeter
    - jmeter_with_dynamic_pools
    - jmeter_dynamic
    - tests

- name: jmeter_slaves
  default: 1
  type: number

- name: jmx
  default: path/to/jmeter/script/bing.jmx
  type: string

- name: jmeter_args
  default: "-Gthreads=1 -Gloops=1 -Gdata_dir=/shared"
  type: string

- name: kubernetes_service_connection
  default: k8
  type: string

- name: arm_service_connection
  default: mygroup
  type: string

variables:
  #user-defined - configure during set-up
  repoName: jmeter_simple_test
  cluster_name: k8
  clusterNodeSize: Standard_D2_v2
  clusterNodeNumber: 2
  rgroup: jmeter-group
  namespace: default

  #adjust paths to repo structure
  crux_file: $(repoName)/path/to/jmeter/config/crux.properties
  thresholds_file: $(repoName)/path/to/jmeter/config/thresholds.properties
  workbooks_file: $(repoName)/path/to/jmeter/config/workbooks.properties
  data_dir_relative: path/to/jmeter/test_data

  #read-only - do not change unless you know what you are doing
  cruxRepoName: crux
  cluster_namespace: crux$(Build.BuildID)
  kubernetesServiceConnection: ${{ parameters.kubernetes_service_connection }}
  scale_up_replicas: ${{ parameters.jmeter_slaves }}
  jmeter_args: ${{ parameters.jmeter_args }}
  scenario: $(repoName)/${{ parameters.jmx }}
  armServiceConnection: ${{ parameters.arm_service_connection }}
  data_dir: $(repoName)/$(data_dir_relative)

jobs:
  - template: run.jmeter.kubernetes.template.yaml
    parameters:
      mode: ${{ parameters.mode }}
      arm_service_connection: ${{ parameters.arm_service_connection }}
      kubernetes_service_connection: ${{ parameters.kubernetes_service_connection }}