parameters:
  - name: mode
    default: jmeter
  - name: linux_pool
    default: microsoft_hosted
  - name: crux_templates
    default: azure/steps
  - name: CUSTOM_crux_templates
    default: /.crux/test/config/custom/steps
  - name: _crux_job_timeout
    default: 60
  - name: _crux_default_step_timeout
    default: 5
  - name: kubernetes_service_connection #used on compile time
    default: _
  - name: arm_service_connection #used on compile time
    default: _

jobs:
  - job: JMeter
    timeoutInMinutes: ${{ parameters._crux_job_timeout }}
    displayName: JMeter pipeline
    #choose pool
    ${{ if eq(parameters.linux_pool, 'microsoft_hosted') }}:
      pool:
        vmImage: 'ubuntu-latest'
    ${{ if ne(parameters.linux_pool, 'microsoft_hosted') }}:
      pool: ${{ parameters.linux_pool }}

    #load up default CRUX variables
    condition: not(eq(variables['jmeter_tests'], false))
    variables:
    - template: azure/default.variables.yaml@crux
      parameters:
        mode: ${{ parameters.mode }}

    steps:
      - ${{ if ne(parameters.mode, 'tests') }}:
        - template: ${{ parameters.crux_templates }}/crux_clone/crux_clone.yaml@crux
          parameters:
            timeoutInMinutes: ${{ parameters._crux_default_step_timeout }}
        - template: ${{ parameters.crux_templates }}/tests_clone/tests_clone.yaml@crux
        - template: ${{ parameters.crux_templates }}/prepare_tests/prepare_tests.yaml@crux
        - template: ${{ parameters.crux_templates }}/validate_configuration/validate_configuration.yaml@crux
          parameters:
            mode: ${{ parameters.mode}}

    #STATIC mode without node pool creation
      - ${{ if and(eq(parameters.mode, 'jmeter'),ne(parameters.kubernetes_service_connection,'_')) }}:
          - template: ${{ parameters.CUSTOM_crux_templates }}/download_secret_file/download_secret_file.yaml
            parameters:
              enabled: false
          - template: ${{ parameters.crux_templates }}/configure_cluster/configure_cluster.yaml@crux
          - template: ${{ parameters.crux_templates }}/create_namespace/create_namespace.yaml@crux
          - template: ${{ parameters.crux_templates }}/deploy_to_cluster/deploy_to_cluster.yaml@crux
          - template: ${{ parameters.crux_templates }}/jmeter_tests/jmeter_tests.yaml@crux
          - template: ${{ parameters.crux_templates }}/workbooks_upload/workbooks_upload.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_report/archive_jmeter_report.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_results/archive_jmeter_results.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_log/archive_jmeter_log.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_errors/archive_jmeter_errors.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_server_logs/archive_jmeter_server_logs.yaml@crux
          - template: ${{ parameters.crux_templates }}/junit/junit.yaml@crux
          - template: ${{ parameters.crux_templates }}/junit_publish/junit_publish.yaml@crux
          - template: ${{ parameters.crux_templates }}/delete_namespace/delete_namespace.yaml@crux

      - ${{ if and(eq(parameters.mode, 'jmeter_with_dynamic_pools'),ne(parameters.kubernetes_service_connection,'_'),ne(parameters.arm_service_connection,'_')) }}:
          - template: ${{ parameters.CUSTOM_crux_templates }}/download_secret_file/download_secret_file.yaml
            parameters:
              enabled: false
          - template: ${{ parameters.crux_templates }}/create_nodepool/create_nodepool.yaml@crux
            parameters:
              mode: ${{ parameters.mode }}
          - template: ${{ parameters.crux_templates }}/configure_cluster/configure_cluster.yaml@crux
          - template: ${{ parameters.crux_templates }}/create_namespace/create_namespace.yaml@crux
          - template: ${{ parameters.crux_templates }}/deploy_to_cluster/deploy_to_cluster.yaml@crux
          - template: ${{ parameters.crux_templates }}/jmeter_tests/jmeter_tests.yaml@crux
          - template: ${{ parameters.crux_templates }}/workbooks_upload/workbooks_upload.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_report/archive_jmeter_report.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_results/archive_jmeter_results.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_log/archive_jmeter_log.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_errors/archive_jmeter_errors.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_server_logs/archive_jmeter_server_logs.yaml@crux
          - template: ${{ parameters.crux_templates }}/junit/junit.yaml@crux
          - template: ${{ parameters.crux_templates }}/junit_publish/junit_publish.yaml@crux
          - template: ${{ parameters.crux_templates }}/delete_namespace/delete_namespace.yaml@crux
          - template: ${{ parameters.crux_templates }}/delete_nodepool/delete_nodepool.yaml@crux
            parameters:
              mode: ${{ parameters.mode }}

      - ${{ if and(eq(parameters.mode, 'jmeter_dynamic'),ne(parameters.arm_service_connection,'_')) }}:
          - template: ${{ parameters.CUSTOM_crux_templates }}/download_secret_file/download_secret_file.yaml
            parameters:
              enabled: false
          - template: ${{ parameters.crux_templates }}/create_cluster/create_cluster.yaml@crux
          - template: ${{ parameters.crux_templates }}/create_nodepool/create_nodepool.yaml@crux
            parameters:
              mode: ${{ parameters.mode }}
          - template: ${{ parameters.crux_templates }}/create_namespace/create_namespace.yaml@crux
          - template: ${{ parameters.crux_templates }}/deploy_to_cluster/deploy_to_cluster.yaml@crux
          - template: ${{ parameters.crux_templates }}/jmeter_tests/jmeter_tests.yaml@crux
          - template: ${{ parameters.crux_templates }}/workbooks_upload/workbooks_upload.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_report/archive_jmeter_report.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_results/archive_jmeter_results.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_log/archive_jmeter_log.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_errors/archive_jmeter_errors.yaml@crux
          - template: ${{ parameters.crux_templates }}/archive_jmeter_server_logs/archive_jmeter_server_logs.yaml@crux
          - template: ${{ parameters.crux_templates }}/junit/junit.yaml@crux
          - template: ${{ parameters.crux_templates }}/junit_publish/junit_publish.yaml@crux
          - template: ${{ parameters.crux_templates }}/delete_namespace/delete_namespace.yaml@crux
          - template: ${{ parameters.crux_templates }}/delete_nodepool/delete_nodepool.yaml@crux
            parameters:
              mode: ${{ parameters.mode }}
          - template: ${{ parameters.crux_templates }}/delete_cluster/delete_cluster.yaml@crux


          #RUN on framework tests
      - ${{ if eq(parameters.mode, 'tests') }}:
        - template: ${{ parameters.crux_templates }}/crux_clone/crux_clone.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/tests_clone/tests_clone.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/prepare_tests/prepare_tests.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/create_cluster/create_cluster.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/create_nodepool/create_nodepool.mock.yaml@crux
          parameters:
            mode: ${{ parameters.mode }}
        - template: ${{ parameters.crux_templates }}/configure_cluster/configure_cluster.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/create_namespace/create_namespace.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/deploy_to_cluster/deploy_to_cluster.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/jmeter_tests/jmeter_tests.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/workbooks_upload/workbooks_upload.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/archive_jmeter_report/archive_jmeter_report.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/archive_jmeter_results/archive_jmeter_results.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/archive_jmeter_log/archive_jmeter_log.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/archive_jmeter_errors/archive_jmeter_errors.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/archive_jmeter_server_logs/archive_jmeter_server_logs.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/junit/junit.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/junit_publish/junit_publish.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/delete_namespace/delete_namespace.mock.yaml@crux
        - template: ${{ parameters.crux_templates }}/delete_nodepool/delete_nodepool.mock.yaml@crux
          parameters:
            mode: ${{ parameters.mode }}
        - template: ${{ parameters.crux_templates }}/delete_cluster/delete_cluster.mock.yaml@crux

  #RUN on framework tests
  - ${{ if eq(parameters.mode, 'tests') }}:
    - template: azure/tests/jobs/run_bats_modules_tests.yaml@crux
    - template: azure/tests/jobs/run_pester_modules_tests.yaml@crux
    - template: azure/tests/jobs/test_docker_images.yaml@crux
    - template: azure/build/jobs/build_and_push_docker.yaml@crux
