name: $(BuildID)
trigger: none
variables:
  cluster_namespace: default #edit
  kubernetesServiceConnection: k8 #edit
  scale_down_replicas: 0
  service: jmeter-slaves
  service-master: jmeter-master

jobs:
  - job: Stop_Tests
    displayName: Stop Tests
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:

    - task: Kubernetes@1
      displayName: Login to cluster
      inputs:
        command: login
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)

    - task: ShellScript@2
      displayName: Stop JMeter tests
      inputs:
        scriptPath: kubernetes/bin/jmeter_stop.sh
        args: $(cluster_namespace)

    - task: KubernetesManifest@0
      displayName: Scale slaves to $(scale_down_replicas)
      inputs:
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        action: scale
        kind: deployment
        name: $(service)
        replicas: $(scale_down_replicas)
        namespace: $(cluster_namespace)

    - task: KubernetesManifest@0
      displayName: Scale master to $(scale_down_replicas)
      inputs:
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        action: scale
        kind: deployment
        name: $(service-master)
        replicas: $(scale_down_replicas)
        namespace: $(cluster_namespace)