steps:
  - bash: |
      echo "Jmeter simple hook 1"
    condition: and(succeeded(), not(eq(variables.pre_hook, false)))
    displayName: User Pre Hook 1

  - bash: |
      echo "Jmeter simple hook 1"
    condition: and(succeeded(), not(eq(variables.pre_hook, false)))
    displayName: User Pre Hook 2